import type { SerieALineupClub, SerieALineupPlayer, SerieALineupSnapshot } from "./serieALineup.js";

type Row = [name: string, pct: number | null, group: "starting" | "bench", slot?: string];

function players(rows: Row[]): SerieALineupPlayer[] {
  return rows.map(([name, pct, lineupGroup, slot]) => ({
    name,
    displayedPercentage: pct,
    lineupGroup,
    slot: slot ?? null,
    rawLabel: pct == null ? `${name} (${lineupGroup})` : `${name} ${pct}% (${lineupGroup}${slot ? ` ${slot}` : ""})`,
  }));
}

function club(name: string, formation: string | null, rows: Row[]): SerieALineupClub {
  return { name, formation, coach: null, players: players(rows) };
}

const CLUBS: SerieALineupClub[] = [
  club("US Sassuolo Calcio", "4-2-3-1", [
    ["Arijanet Murić", 80, "starting", "GK"],
    ["S. Turati", 20, "bench", "GK"],
    ["Sebastian Walukiewicz", 60, "starting", "RB"],
    ["F. Missoni", 40, "bench", "RB"],
    ["Fali Candé", 60, "starting", "CB"],
    ["Jay Idzes", 90, "starting", "CB"],
    ["Josh Doig", 90, "starting", "LB"],
    ["Nemanja Matić", 90, "starting", "CDM"],
    ["Luca Lipani", 60, "starting", "CDM"],
    ["Domenico Berardi", 90, "starting", "RW"],
    ["Kristian Thorstvedt", 90, "starting", "CAM"],
    ["Armand Laurienté", 90, "starting", "LW"],
    ["Andrea Pinamonti", 90, "starting", "ST"],
    ["K. Bowie", 10, "bench", "ST"],
    ["Samuele Mulattieri", null, "bench"],
    ["Nicholas Pierini", null, "bench"],
    ["Luca Moro", null, "bench"],
    ["Ismaël Koné", null, "bench"],
  ]),
  club("US Lecce", "4-2-3-1", [
    ["Wladimiro Falcone", 90, "starting", "GK"],
    ["Antonino Gallo", 90, "starting", "LB"],
    ["Tiago Gabriel", 80, "starting", "CB"],
    ["Jamil Siebert", 60, "starting", "CB"],
    ["Gaspar", 40, "bench", "CB"],
    ["Danilo Veiga", 90, "starting", "RB"],
    ["Medon Berisha", 60, "starting", "CDM"],
    ["Lassana Coulibaly", 90, "starting", "CDM"],
    ["Lameck Banda", 60, "starting", "LW"],
    ["Omri Gandelman", 60, "starting", "CAM"],
    ["Santiago Pierotti", 90, "starting", "RW"],
    ["Nikola Štulić", 60, "starting", "ST"],
    ["Konan Jocelyn N’Dri", null, "bench"],
    ["Youssef Maleh", null, "bench"],
    ["Corrie Ndaba", null, "bench"],
    ["Gaby Jean", null, "bench"],
    ["Sadik Fofana", null, "bench"],
  ]),
  club("Udinese Calcio", "3-5-2", [
    ["Maduka Okoye", 90, "starting", "GK"],
    ["Oumar Solet", 90, "starting", "CB"],
    ["Thomas Kristensen", 90, "starting", "CB"],
    ["Christian Kabasele", 90, "starting", "CB"],
    ["Hassane Kamara", 90, "starting", "LWB"],
    ["Unai Gómez", 60, "starting", "CM"],
    ["J. Piotrowski", 40, "bench", "CM"],
    ["Jesper Karlström", 90, "starting", "CDM"],
    ["Jurgen Ekkelenkamp", 90, "starting", "CM"],
    ["Mërgim Vojvoda", 90, "starting", "RWB"],
    ["Nicolò Zaniolo", 90, "starting", "ST"],
    ["Keinan Davis", 80, "starting", "ST"],
    ["V. Bayo", 10, "bench", "ST"],
    ["I. Gueye", 10, "bench", "ST"],
    ["Jordan Zemura", null, "bench"],
  ]),
  club("Torino FC", "3-4-2-1", [
    ["Lucas Perri", 60, "starting", "GK"],
    ["A. Paleari", 30, "bench", "GK"],
    ["Pietro Comuzzo", 90, "starting", "CB"],
    ["Saúl Coco", 90, "starting", "CB"],
    ["Ardian Ismajli", 90, "starting", "CB"],
    ["Gvidas Gineitis", 90, "starting", "CM"],
    ["Cesare Casadei", 90, "starting", "CM"],
    ["Marcus Pedersen", 90, "starting", "RWB"],
    ["Ché Adams", 70, "starting", "AM"],
    ["G. Oristanio", 30, "bench", "AM"],
    ["Nikola Vlašić", 90, "starting", "AM"],
    ["Giovanni Simeone", 80, "starting", "ST"],
    ["D. Zapata", 20, "bench", "ST"],
    ["T. Anjorin", null, "bench"],
    ["Adrien Tameze", null, "bench"],
    ["Zakaria Aboukhlal", null, "bench"],
  ]),
  club("SSC Napoli", "4-3-3", [
    ["Vanja Milinković-Savić", 60, "starting", "GK"],
    ["A. Meret", 40, "bench", "GK"],
    ["Leonardo Spinazzola", 60, "starting", "LB"],
    ["M. Olivera", 40, "bench", "LB"],
    ["Benoît Badiashile", 80, "starting", "CB"],
    ["Amir Rrahmani", 80, "starting", "CB"],
    ["S. Beukema", 10, "bench", "CB"],
    ["Giovanni Di Lorenzo", 90, "starting", "RB"],
    ["Scott McTominay", 90, "starting", "CM"],
    ["Stanislav Lobotka", 90, "starting", "CM"],
    ["Kevin De Bruyne", 90, "starting", "CM"],
    ["Alisson Santos", 60, "starting", "LW"],
    ["M. Politano", 20, "bench", "LW"],
    ["Rasmus Højlund", 90, "starting", "ST"],
    ["David Neres", 60, "starting", "RW"],
    ["Alessandro Buongiorno", null, "bench"],
    ["Nikita Contini Baranovsky", null, "bench"],
    ["André-Frank Zambo Anguissa", null, "bench"],
    ["Billy Gilmour", null, "bench"],
  ]),
  club("US Cremonese", null, [
    ["Andrea Fulignati", 80, "starting", "GK"],
    ["M. Festa", 20, "bench", "GK"],
  ]),
  club("Parma Calcio 1913", "3-5-1-1", [
    ["Zion Suzuki", 70, "starting", "GK"],
    ["E. Corvi", 30, "bench", "GK"],
    ["Lautaro Valenti", 90, "starting", "CB"],
    ["Alessandro Circati", 90, "starting", "CB"],
    ["Mariano Troilo", 70, "starting", "CB"],
    ["S. Britschgi", 30, "bench", "CB"],
    ["Emanuele Valeri", 90, "starting", "LWB"],
    ["Hans Nicolussi Caviglia", 60, "starting", "CM"],
    ["O. Sørensen", 40, "bench", "CM"],
    ["Mandela Keita", 90, "starting", "CM"],
    ["Adrián Bernabé", 90, "starting", "CM"],
    ["Enrico Delprato", 90, "starting", "RWB"],
    ["Jacob Ondrejka", 90, "starting", "AM"],
    ["David Romero", 60, "starting", "ST"],
    ["Benjamin Cremaschi", null, "bench"],
  ]),
  club("Hellas Verona FC", "4-3-2-1", [
    ["Nicola Leali", 80, "starting", "GK"],
    ["L. Montipò", 20, "bench", "GK"],
    ["Martin Frese", 80, "starting", "RB"],
    ["R. Belghali", 20, "bench", "RB"],
    ["Tobias Slotsager", 70, "starting", "CB"],
    ["N. Calabrese", 30, "bench", "CB"],
    ["Andrias Edmundsson", 90, "starting", "CB"],
    ["Daniel Oyegoke", 70, "starting", "LB"],
    ["S. Korać", 30, "bench", "LB"],
    ["Tomáš Suslov", 80, "starting", "CM"],
    ["R. Gagliardini", 30, "bench", "CM"],
    ["Antoine Bernede", 70, "starting", "CM"],
    ["Suat Serdar", 70, "starting", "CM"],
    ["G. Kastanos", 30, "bench", "CM"],
    ["Dailon Livramento", 70, "starting", "AM"],
    ["A. Sarr", 30, "bench", "AM"],
    ["Mattia Compagnon", 80, "starting", "AM"],
    ["D. Mosquera", 20, "bench", "AM"],
    ["Samuele Mulattieri", 80, "starting", "ST"],
  ]),
  club("Genoa CFC", "3-4-2-1", [
    ["Justin Bijlow", 90, "starting", "GK"],
    ["F. Stolz", 10, "bench", "GK"],
    ["Leo Østigård", 90, "starting", "CB"],
    ["Alessandro Marcandalli", 90, "starting", "CB"],
    ["S. Otoa", 10, "bench", "CB"],
    ["Johan Vásquez", 90, "starting", "CB"],
    ["Brooke Norton-Cuffy", 90, "starting", "RWB"],
    ["S. Sabelli", 10, "bench", "RWB"],
    ["Morten Frendrup", 80, "starting", "CM"],
    ["Alex Amorim", 20, "bench", "CM"],
    ["Djibril Sow", 80, "starting", "CM"],
    ["E. Meichtry", 20, "bench", "CM"],
    ["Mikael Ellertsson", 60, "starting", "LWB"],
    ["M. Mitaj", 30, "bench", "LWB"],
    ["D. Puczka", 10, "bench", "LWB"],
    ["Hamed Traorè", 60, "starting", "AM"],
    ["Vitinha", 40, "bench", "AM"],
    ["Tommaso Baldanzi", 80, "starting", "AM"],
    ["Junior Messias", 10, "bench", "AM"],
    ["S. Wiafe", 10, "bench", "AM"],
    ["Lorenzo Colombo", 80, "starting", "ST"],
    ["E. Havel", 10, "bench", "ST"],
  ]),
  club("SS Lazio", "4-3-3", [
    ["Ivan Provedel", 70, "starting", "GK"],
    ["C. Mandas", 30, "bench", "GK"],
    ["Adam Marušić", 80, "starting", "RB"],
    ["M. Lazzari", 10, "bench", "RB"],
    ["E. Hysaj", 10, "bench", "RB"],
    ["Alessio Romagnoli", 80, "starting", "CB"],
    ["O. Provstgaard", 10, "bench", "CB"],
    ["Mario Gila", 80, "starting", "CB"],
    ["S. Gigot", 10, "bench", "CB"],
    ["Patric", 10, "bench", "CB"],
    ["Nuno Tavares", 80, "starting", "LB"],
    ["Pellegrini", 20, "bench", "LB"],
    ["Mattéo Guendouzi", 90, "starting", "CM"],
    ["Nicolò Rovella", 80, "starting", "CDM"],
    ["D. Cataldi", 10, "bench", "CDM"],
    ["Fisayo Dele-Bashiru", 60, "starting", "CM"],
    ["R. Belahyane", 40, "bench", "CM"],
    ["Gustav Isaksen", 60, "starting", "RW"],
    ["M. Cancellieri", 20, "bench", "RW"],
    ["Pedro", 20, "bench", "RW"],
    ["Taty Castellanos", 80, "starting", "ST"],
    ["B. Dia", 20, "bench", "ST"],
    ["Mattia Zaccagni", 90, "starting", "LW"],
    ["T. Noslin", 10, "bench", "LW"],
    ["Toma Bašić", null, "bench"],
  ]),
  club("Juventus FC", "4-2-3-1", [
    ["Michele Di Gregorio", 60, "starting", "GK"],
    ["G. Vicario", 40, "bench", "GK"],
    ["Zeki Çelik", 80, "starting", "RB"],
    ["P. Kalulu", 40, "bench", "LB"],
    ["Jhon Lucumí", 80, "starting", "CB"],
    ["Bremer", 70, "starting", "CB"],
    ["L. Kelly", 30, "bench", "CB"],
    ["Andrea Cambiaso", 60, "starting", "LB"],
    ["Manuel Locatelli", 90, "starting", "CM"],
    ["Weston McKennie", 60, "starting", "CM"],
    ["Douglas Luiz", 40, "bench", "CM"],
    ["Francisco Conceição", 80, "starting", "RM"],
    ["Kenan Yıldız", 90, "starting", "CAM"],
    ["Kerim-Sam Alajbegović", 70, "starting", "LM"],
    ["E. Zhegrova", 30, "bench", "LM"],
    ["Randal Kolo Muani", 80, "starting", "ST"],
    ["J. David", 20, "bench", "ST"],
  ]),
  club("Calcio Como", "4-2-3-1", [
    ["Jean Butez", 90, "starting", "GK"],
    ["Ivan Smolčić", 60, "starting", "RB"],
    ["Ignace Van der Brempt", 40, "bench", "RB"],
    ["Marc Oliver Kempf", 70, "starting", "CB"],
    ["Jacobo Ramón", 90, "starting", "CB"],
    ["Álex Valle", 60, "starting", "LB"],
    ["Kaiki", 40, "bench", "LB"],
    ["Maximo Perrone", 60, "starting", "DM"],
    ["Luis Milla", 40, "bench", "DM"],
    ["Lucas da Cunha", 70, "starting", "DM"],
    ["M. Caqueret", 20, "bench", "DM"],
    ["Assane Diao", 60, "starting", "AMR"],
    ["Jesús Rodríguez", 40, "bench", "AMR"],
    ["Nicolás Paz", 90, "starting", "AMC"],
    ["Martin Baturina", 70, "starting", "AML"],
    ["J. Addai", 10, "bench", "AML"],
    ["N. Kühn", 10, "bench", "AML"],
    ["Tasos Douvikas", 80, "starting", "ST"],
    ["Álvaro Morata", 20, "bench", "ST"],
    ["Mauro Vigorito", null, "bench"],
    ["Mattia Liberali", null, "bench"],
  ]),
  club("Cagliari Calcio", "4-3-3", [
    ["Elia Caprile", 90, "starting", "GK"],
    ["Adam Obert", 90, "starting", "LB"],
    ["Juan Rodríguez", 60, "starting", "CB"],
    ["Yerry Mina", 90, "starting", "CB"],
    ["Zé Pedro", 60, "starting", "RB"],
    ["Jacopo Fazzini", 90, "starting", "CM"],
    ["Alessandro Romano", 60, "starting", "CM"],
    ["Michel Adopo", 90, "starting", "CM"],
    ["Daniel Maldini", 90, "starting", "LW"],
    ["Gennaro Borrelli", 60, "starting", "ST"],
    ["Mattia Felici", 60, "starting", "RW"],
    ["Leonardo Pavoletti", null, "bench"],
  ]),
  club("Atalanta Bergamasca Calcio", "4-3-3", [
    ["Marco Carnesecchi", 90, "starting", "GK"],
    ["M. Sportiello", 10, "bench", "GK"],
    ["Lorenzo Bernasconi", 60, "starting", "LB"],
    ["H. Ahanor", 40, "bench", "LB"],
    ["Isak Hien", 60, "starting", "CB"],
    ["S. Kolašinac", 40, "bench", "CB"],
    ["Giorgio Scalvini", 60, "starting", "CB"],
    ["Davide Zappacosta", 60, "starting", "RB"],
    ["R. Bellanova", 40, "bench", "RB"],
    ["Éderson", 60, "starting", "CM"],
    ["Marten de Roon", 60, "starting", "CM"],
    ["Gianluca Gaetano", 60, "starting", "CM"],
    ["L. Samardžić", 40, "bench", "CM"],
    ["Giacomo Raspadori", 60, "starting", "LW"],
    ["Gianluca Scamacca", 60, "starting", "ST"],
    ["N. Krstović", 40, "bench", "ST"],
    ["Charles De Ketelaere", 60, "starting", "RW"],
    ["Francesco Rossi", null, "bench"],
    ["Yunus Musah", null, "bench"],
  ]),
  club("Bologna FC 1909", "4-3-3", [
    ["Lukasz Skorupski", 90, "starting", "GK"],
    ["M. Pessina", 10, "bench", "GK"],
    ["Juan Miranda", 90, "starting", "LB"],
    ["R. Alhassane", 10, "bench", "LB"],
    ["Torbjorn Heggem", 90, "starting", "CB"],
    ["N. Casale", 10, "bench", "CB"],
    ["Eivind Helland", 70, "starting", "CB"],
    ["M. Vitik", 30, "bench", "CB"],
    ["Emil Holm", 70, "starting", "RB"],
    ["N. Zortea", 30, "bench", "RB"],
    ["Lewis Ferguson", 60, "starting", "CM"],
    ["T. Pobega", 40, "bench", "CM"],
    ["Federico Bernardeschi", 60, "starting", "CM"],
    ["M. Amondarain", 20, "bench", "CM"],
    ["Nikola Moro", 60, "starting", "CM"],
    ["O. El Azzouzi", 20, "bench", "CM"],
    ["Jonathan Rowe", 60, "starting", "LW"],
    ["N. Cambiaghi", 40, "bench", "LW"],
    ["Artem Dovbyk", 70, "starting", "ST"],
    ["R. Piccoli", 30, "bench", "ST"],
    ["Riccardo Orsolini", 60, "starting", "RW"],
    ["Lorenzo De Silvestri", null, "bench"],
  ]),
  club("FC Internazionale Milano", "3-5-2", [
    ["Yann Sommer", 90, "starting", "GK"],
    ["Alessandro Bastoni", 90, "starting", "CB"],
    ["Yann Bisseck", 60, "starting", "CB"],
    ["F. Acerbi", 40, "bench", "CB"],
    ["Manuel Akanji", 90, "starting", "CB"],
    ["Federico Dimarco", 90, "starting", "LWB"],
    ["Piotr Zieliński", 60, "starting", "CM"],
    ["H. Mkhitaryan", 40, "bench", "CM"],
    ["Hakan Çalhanoğlu", 90, "starting", "CM"],
    ["Nicolò Barella", 90, "starting", "CM"],
    ["Denzel Dumfries", 90, "starting", "RWB"],
    ["Lautaro Martínez", 90, "starting", "ST"],
    ["Marcus Thuram", 90, "starting", "ST"],
    ["Josep Martínez", null, "bench"],
    ["Matteo Darmian", null, "bench"],
    ["Tiago Palacios", null, "bench"],
    ["Carlos Augusto", null, "bench"],
    ["Andy Diouf", null, "bench"],
    ["Davide Frattesi", null, "bench"],
  ]),
  club("AS Roma", "3-4-2-1", [
    ["Svilar", 90, "starting", "GK"],
    ["Evan Ndicka", 90, "starting", "CB"],
    ["Gianluca Mancini", 90, "starting", "CB"],
    ["Mario Hermoso", 60, "starting", "CB"],
    ["D. Ghilardi", 40, "bench", "CB"],
    ["Wesley", 90, "starting", "LWB"],
    ["Manu Koné", 90, "starting", "CM"],
    ["N. El Aynaoui", 10, "bench", "CM"],
    ["Bryan Cristante", 90, "starting", "CM"],
    ["Nahuel Molina", 90, "starting", "RWB"],
    ["D. Rensch", 10, "bench", "RWB"],
    ["Matías Soulé", 90, "starting", "AM"],
    ["Paulo Dybala", 60, "starting", "AM"],
    ["Donyell Malen", 90, "starting", "ST"],
    ["S. Castro", 10, "bench", "ST"],
    ["Robinio Vaz", null, "bench"],
    ["Niccolò Pisilli", null, "bench"],
    ["Lorenzo Pellegrini", null, "bench"],
  ]),
  club("AC Pisa 1909", "4-3-3", [
    ["Adrian Semper", 70, "starting", "GK"],
    ["A. Vuković", 30, "bench", "GK"],
    ["Samuele Angori", 60, "starting", "LB"],
    ["M. Léris", 30, "bench", "LB"],
    ["J. Mbambi", 10, "bench", "LB"],
    ["Simone Canestrelli", 80, "starting", "CB"],
    ["F. Coppola", 20, "bench", "CB"],
    ["Antonio Caracciolo", 60, "starting", "CB"],
    ["Lusuardi", 40, "bench", "CB"],
    ["Simone Zanon", 70, "starting", "RB"],
    ["A. Calabresi", 30, "bench", "RB"],
    ["Giuseppe Leone", 80, "starting", "DM"],
    ["M. Højholt", 20, "bench", "DM"],
    ["İsak Vural", 60, "starting", "CM"],
    ["Tomás Esteves", 40, "bench", "CM"],
    ["Michel Aebischer", 70, "starting", "CM"],
    ["I. Touré", 30, "bench", "CM"],
    ["Emanuele Rao", 80, "starting", "LW"],
    ["M. Tramoni", 20, "bench", "LW"],
    ["Tommaso Marras", 70, "starting", "RW"],
    ["I. Ferrah", 30, "bench", "RW"],
    ["Stefano Moreo", 70, "starting", "ST"],
    ["H. Meister", 30, "bench", "ST"],
  ]),
  club("ACF Fiorentina", "4-3-3", [
    ["David de Gea", 90, "starting", "GK"],
    ["O. Christensen", 10, "bench", "GK"],
    ["Viery", 60, "starting", "LB"],
    ["Marin Pongracic", 90, "starting", "CB"],
    ["L. Ranieri", 10, "bench", "CB"],
    ["Radu Drăgușin", 90, "starting", "CB"],
    ["P. Comuzzo", 10, "bench", "CB"],
    ["Dodô", 90, "starting", "RB"],
    ["Arthur Atta", 80, "starting", "CM"],
    ["C. Ndour", 20, "bench", "CM"],
    ["Christ Inao Oulaï", 70, "starting", "CM"],
    ["R. Mandragora", 30, "bench", "CM"],
    ["Nicolò Fagioli", 90, "starting", "CM"],
    ["Albert Guðmundsson", 80, "starting", "LW"],
    ["Moise Kean", 70, "starting", "ST"],
    ["M. Pellegrino", 30, "bench", "ST"],
    ["Franco Mastantuono", 90, "starting", "RW"],
    ["Luca Lezzerini", null, "bench"],
    ["Niccolò Fortini", null, "bench"],
    ["Álex Jiménez", null, "bench"],
  ]),
  club("AC Milan", "3-4-3", [
    ["Mike Maignan", 90, "starting", "GK"],
    ["P. Terracciano", 10, "bench", "GK"],
    ["Strahinja Pavlović", 60, "starting", "CB"],
    ["Mario Gila", 90, "starting", "CB"],
    ["Matteo Gabbia", 60, "starting", "CB"],
    ["F. Tomori", 40, "bench", "CB"],
    ["Davide Bartesaghi", 80, "starting", "LM"],
    ["Adrien Rabiot", 70, "starting", "CM"],
    ["Y. Fofana", 30, "bench", "CM"],
    ["Ardon Jashari", 60, "starting", "CM"],
    ["L. Modrić", 40, "bench", "CM"],
    ["Alexis Saelemaekers", 80, "starting", "RM"],
    ["Rafael Leão", 60, "starting", "LW"],
    ["C. Nkunku", 40, "bench", "LW"],
    ["Gonçalo Ramos", 90, "starting", "ST"],
    ["Christian Pulišić", 60, "starting", "RW"],
    ["S. Chukwueze", 20, "bench", "RW"],
    ["Lorenzo Torriani", null, "bench"],
    ["Ruben Loftus-Cheek", null, "bench"],
  ]),
];

export function sorareInsideSnapshot(
  extractedAt = "2026-08-16T14:00:00.000Z",
): SerieALineupSnapshot {
  return {
    source: "sorareinside",
    sourceUrl: "https://sorareinside.com",
    title: "SorareInside Serie A team profiles 2026/27",
    extractedAt,
    clubs: CLUBS,
  };
}
